### ISSUE TITLE
Front End Form, Not loading Tooltip icon or popup.

### ISSUE THREAD

**Issue by nuresponse** [tmconnect/ACF-Tooltip#1]
This plugin is awesome, saved me a ton of time.  I am using front end acf_form(), to allow user to post a "customer review", I can see the markup in the front end, but not the "?" icon or popup tooltip.  I'm assuming it's as simple as a .js file that isn't enqueued for the front end of the site.  Can you let me know where i can find the scripts to enqueue, or if there's more than that, can you point me in the right direction.

Here's some images 
- Showing Admin is working:
![image](https://cloud.githubusercontent.com/assets/981804/10008303/f65c78fc-6081-11e5-9a24-851c3a3d3ae4.png)

- Showing Front End Form UI, not working
![image](https://cloud.githubusercontent.com/assets/981804/10008308/013d5d04-6082-11e5-9f4f-2a71ce21ed00.png)

- Showing Front End Code Inspector the markup is loaded:
![image](https://cloud.githubusercontent.com/assets/981804/10008322/1fc16d10-6082-11e5-9eb4-bbb19f1d1df5.png)

Thanks for your help!

**Comment by tmconnect** [comment]
I've never tried it on the front end - but my first test today works as expected on the front end.

Maybe there is a JS error on front end that blocked all further JS execution. Please take a look at the Code Inspector Console and let me know.

Can you confirm that all the following JS- and CSS-files are loaded correctly

- acf-tooltip-v5.js
- acf-tooltip.css
- jquery.qtip.min.js
- jquery.qtip.min.css

Cheers
Thomas

**Comment by nuresponse** [comment]
Here's the page it's on, The form is hidden on page load, use the "Write A
Review" large red accordion button to display it.
http://jmbodyshops.nuhelpdesk.com/reviews/

Yes, I verified that all 4 files are loaded.
I'm not very familiar with js conflict testing, is there something I should
do to test for conflicts?
I am running another ACF plugin called: ACF Star Rating.

Mark Dayley
nuRESPONSE
888-862-6160 ext. 21
mark@nuresponse.com
"In a tight economy, it's important to market Smarter! . . not more!"

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by tmconnect** [comment]
I took a look at your side and found what's the problem:

If I load the ACF form on my test site, automatically the **/wp-includes/css/dashicons.min.css** is loaded. This doesn't happen on your site. I don't know why, but maybe it causes of your ACF form.

Secondly there's a style for the class **.tooltip** in the **/wp-content/themes/MotorMedia_JointsWP/assets/vendor/foundation/css/foundation.min.css** of your theme that's hiding the .tooltip span.

The solution for your site would be to enqueue the **/wp-includes/css/dashicons.min.css** like this

```<?php
add_action( 'wp_enqueue_scripts', 'mytheme_scripts' );
/**
 * Enqueue Dashicons style for frontend use
 */
function mytheme_scripts() {
	wp_enqueue_style( 'dashicons' );
}
```
and remove the .tooltip class in your foundation.min.css.

After this changes the tooltip icon will be shown and the tooltips will work.

Hope this helps
Thomas
