### ISSUE TITLE
Tooltips break due to not escaping quotes used in instructions

### ISSUE THREAD

**Issue by digiltd** [tmconnect/ACF-Tooltip#2]
Hi

Thanks for the plugin. Unfortunately it breaks when special characters are used in the instructions.

The problem is the text content of the tips is placed and then taken from a title attribute.

A fix could be to change the way you use qTips to instead get the actual html span element as the tip.

Thanks

**Comment by tmconnect** [comment]
Thanks for the idea to use qTip in anther way!

Please check out the new version that should fix this issue.

**Comment by digiltd** [comment]
Works perfectly, thanks
