### ISSUE TITLE
Tooltips don't show on front end pages

### ISSUE THREAD

**Issue by prelude34** [tmconnect/ACF-Tooltip#6]
Works fine in the admin panel but don't show up on the front end page. 
They should show up on this page: http://obitanywhere.com/edit-obit/?postid=290
I've swapped themes to test but that doesn't seem to change anything.
Thanks in advance!

**Comment by tmconnect** [comment]
Sorry, but I didn't have much experience with front end edit.

Please try this version (https://dl.dropboxusercontent.com/u/3442276/acf-tooltip.zip) and let me know if this works for you on front end.

Thanks
Thomas

**Comment by prelude34** [comment]
Update. Thanks for your quick reply. I realized that the problem was on my end. In my code, I had accidentally removed <?php acf_form_head(); ?>
Put it back in and everything works as advertised. 
Awesome plugin.
