### ISSUE TITLE
Fields positioned below fields do not show tooltip

### ISSUE THREAD

**Issue by ZachTRice** [tmconnect/ACF-Tooltip#7]
The tooltip does not appear when the instructions are position below the fields; it only works when the field is positioned below the label. This is a bit of a minor issue but an issue nontheless.

View of fields before enabling plugin:
![before](https://cloud.githubusercontent.com/assets/17348884/16020390/e2ac5176-317b-11e6-947d-02184bd21557.png)
View of field after enabling plugin:
![after](https://cloud.githubusercontent.com/assets/17348884/16020395/e4791fac-317b-11e6-8407-965578b46698.png)

**Comment by tmconnect** [comment]
This has nothing to do with fields with a width less than 100% - it's only because the instructions are set below the fields.

Even if the easiest solution is to set the instructions below the labels, I make some changes to show the instruction button in this situation.

**Comment by ZachTRice** [comment]
My bad, I meant to update the title before I posted. 

Yep, It's a minor issue for sure; just wanted to point it out in case you weren't aware. I think better UI might be add to a third option to the "Instruction placement" select. Based on that selection add a class to the instruction field display then attach your JS to that.

I see you made an update earlier, so I'll check that out. All in all very nice plugin.

**Comment by byron222** [comment]
My Tooltips dont work too...

what can i do??

**Comment by tmconnect** [comment]
Please check new version 1.1.6

**Comment by byron222** [comment]
thank you.

i uploaded but still not working....
i have the latest version of ACF 5.3.9.2

**Comment by byron222** [comment]
i dont know but i change the acf-tooltop-v5.php and works....

this is how i change
`<?php
global $pagenow;

$enqueue = true;

add_action( 'acf/input/admin_enqueue_scripts', 'enqueue_acf_tooltip' );

function enqueue_acf_tooltip() {

    wp_enqueue_script( 'acf_tooltip_script', plugin_dir_url( __FILE__ ) . '/js/acf-tooltip-v5.js', array('jquery-qtip') );
    wp_enqueue_style( 'acf_tooltip_css', plugin_dir_url( __FILE__ ) . '/css/acf-tooltip.css' );
    wp_enqueue_script( 'jquery-qtip', plugin_dir_url( __FILE__ ) . '/js/jquery.qtip.min.js' );
	wp_enqueue_style( 'jquery-qtip.js', plugin_dir_url( __FILE__ ) . '/css/jquery.qtip.min.css' );
	wp_enqueue_style( 'dashicons' );
	
}

?>`

**Comment by tmconnect** [comment]
o.k. - I see, you deleted the check if you on an post/page edit screen. This check is included to only show the tooltips on this pages and not on the ACF field group editor pages.

But i missed that this check only works for editing an existing post or page. Please include this check again and change line 6 from

```if ( isset($_GET['post']) && $pagenow == "post.php" ) {```

to

```if ( isset($_GET['post']) && $pagenow == "post.php" || $pagenow == "post-new.php" ) {```

Please let me know if it works.

**Comment by byron222** [comment]
thank U!!!!

this is perfect!!!!

thank u so much again!!!

**Comment by tmconnect** [comment]
Thanks for your feedback. Added this to the new version 1.1.7
