### ISSUE TITLE
Make configurable

### ISSUE THREAD

**Issue by Hube2** [tmconnect/ACF-Tooltip#8]
I'm working on a project where I need tooltips, but the styles you're using are wrong form me. It would be great if the styles were configurable. I don't want to reinvent this. First is the work involved and second is the fact that I'm pretty sure after examining the code that if I add my own tooltips and someone also install this on the same site that there would be several conflicts that wouldn't be easy to correct.

That said, I'd be willing to work on it. My thought would be to add an acf options page under the settings menu with options to
1) Select what field groups to apply tooltips to, default would be all
2) Set the color of the tooltip icon, the default would the current color
3) Set the style, location, etc for tooltips, defaults would be your current settings.

I plan on doing the work anyway, just wondering if you're at all interested in a pull request, or several.

Of course I'd be happy to discuss my proposed changes.

Let me know,

~JH

**Comment by tmconnect** [comment]
Hi John,

this is an approach that I have not thought about yet. But of course it has something for flexibility.

I think, in most cases this feature would be used by developers, so for me it's not the best solution to do this within an options page. What do you think of filters for that.

Also, I would not want to define which field type is provided for tooltips. What if you want to show a description on one field of a field type, but not on all other fields of the same type. Sure, that's a strange scenario - but it can happen.
My first idea for solving this, would be a class for the fields thats responsible to apply the tooltip or not.

For the color, the style, the location etc. a filter could do the work as well. Reading the filter in the main plugin file and apply the settings to the ln10 var for later use in the JS-file would be the easiest way.

What do you think about this?

Cheers
Thomas

**Comment by Hube2** [comment]
Filters would work for me as well, and be a bit easier, no settings to get. 

but the you said "ln10 var" you lost me.

I could do it by localizing your acf-toolip-v5.js. Even so, the styles are in a css file so those would need to be move and set with JS, which could complicate matters.

My main concern here is that I'm building a plugin. The acf fields that I'm using will eventually have tooltips and I want these tooltips to match the rest of the custom UI that I'm building. Since your plugin adds tooltips to all acf fields then I'm looking at a conflict that I don't think I can resolve should someone decide to add both plugins. The easiest solution to avoid that for me would be by using your plugin ins some way.

**Comment by tmconnect** [comment]
Hi John,

Please give me an email to which I can send a test version, in which I have implemented your idea.

Cheers
Thomas

**Comment by tmconnect** [comment]
New version now online...
